version: '3.4'

networks:
  appnetwork:

services:
  rutinedb:
    container_name: rutinedb
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: pass1234
    ports:
       - 3306:3306
    networks:
       - appnetwork

  rutine.api:
    container_name: rutine-api
    image: ${DOCKER_REGISTRY-}rutineapi
    build:
      context: .
      dockerfile: Rutine.Api/Dockerfile
    depends_on:
       - rutinedb
    networks:
       - appnetwork

  membersdb:
    container_name: membersdb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
       - 27017:27017
    networks:
       - appnetwork

  members.api:
    container_name: members-api
    image: ${DOCKER_REGISTRY-}membersapi
    build:
      context: .
      dockerfile: Members.Api/Dockerfile 
    depends_on:
       - membersdb
    networks:
       - appnetwork

  paymentdb:
    container_name: paymentdb
    image: container-registry.oracle.com/database/express:latest
    environment:
       ORACLE_PWD: password
    ports:
       - "1521:1521"
       - "5500:5500"

  
  payment.api:
    container_name: payment-api
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Payment.Api/Dockerfile
    depends_on:
       - paymentdb  
    networks:
       - appnetwork
